
export const LOAD_ANALYTICS_SUMMARY = 'LOAD_ANALYTICS_SUMMARY'
export const SET_ANALYTICS_SUMMARY = 'SET_ANALYTICS_SUMMARY'

export const LOAD_VENTURE_DETAILS = 'LOAD_VENTURE_DETAILS'
export const SET_VENTURE_DETAILS = 'SET_VENTURE_DETAILS'
